### ISSUE TITLE
Glossary and List of Symbols missing

### ISSUE THREAD

**Issue by happyTonakai** [kevinhughes27/ThesisTemplate#2]
Hi.

To keep the root directory clean, I move all the `.tex` files to a new folder `/Tex`, and change all `\include{FileName}` to `\inclde{Tex/FileName}` in the `Thesis.tex`.

(`Thesis.tex` is still in the root directory.)

However, the compiled pdf file does not contain `Glossary` and `List of Symbols`. I'm sure that glossary and list of symbols are uncommented in `0_Preamble.tex`. What is going wrong?

**Comment by kevinhughes27** [comment]
It's been a while but I'll try and provide what limited support I'm able to.

You are building with the `regenerate.sh` script right? It has to do two passes, the first one builds the glossary, bibtex etc and the second rebuilds and uses those new files. There should be a bunch of other files created.

Second, did you try running it before making any changes? might be a good idea just to make the original code is working on your machine.

Sounds like a nice organization you are working on, PRs are welcome :)
